/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProductLazyImport = createFileRoute('/Product')()
const IndexLazyImport = createFileRoute('/Index')()
const CheckoutLazyImport = createFileRoute('/Checkout')()

// Create/Update Routes

const ProductLazyRoute = ProductLazyImport.update({
  path: '/Product',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Product.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/Index',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Index.lazy').then((d) => d.Route))

const CheckoutLazyRoute = CheckoutLazyImport.update({
  path: '/Checkout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Checkout.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Checkout': {
      preLoaderRoute: typeof CheckoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/Index': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Product': {
      preLoaderRoute: typeof ProductLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  CheckoutLazyRoute,
  IndexLazyRoute,
  ProductLazyRoute,
])

/* prettier-ignore-end */
