import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <main classdata-name="">
        <Head>
          <title>STYLiSH</title>
          <meta data-name="description" content="Generated by create-t3-app" />
          <link
            rel="shortcut icon"
            href="https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg"
            type="image/x-icon"
          />
        </Head>

        <nav classdata-name="fixed top-0 z-[999] w-full mobile:h-[102px] desktop:h-[140px]">
          <div
            classdata-name="
            flex
            bg-[#ffffff]
            mobile:h-[52px] mobile:items-center mobile:justify-center
            desktop:h-[100px]
            desktop:flex-row
            desktop:items-center
            desktop:justify-start
          "
            data-name="top-nav-bar-box"
          >
            <div data-name="top-nav-bar-website-logo-link">
              <img
                classdata-name="
                cursor-pointer
                mobile:h-[24px] mobile:w-[129px]
                desktop:ml-[60px] desktop:h-[48px] desktop:w-[258px]
              "
                src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055669914406982/logo.png"
                alt=""
                data-name="top-nav-bar-website-logo"
              />
            </div>
            <div
              classdata-name="
              mobile:hidden
              desktop:mt-[15px]
              desktop:ml-[95px]
              desktop:block
              desktop:cursor-pointer
              desktop:border-r-[1px]
              desktop:border-solid
              desktop:border-[#3F3A3A]
              desktop:text-center
              desktop:text-[20px]
              desktop:leading-[28px]
              desktop:tracking-[30px]
              desktop:text-[#3F3A3A]
              desktop:hover:text-[#8B572A]
            "
              data-name="top-nav-bar-desktop-women-dresses"
            >
              <div data-name="top-nav-bar-desktop-women-dresses-link">女裝</div>
            </div>
            <div
              classdata-name="
              mobile:hidden
              desktop:mt-[15px]
              desktop:ml-[36px]
              desktop:block
              desktop:cursor-pointer
              desktop:border-r-[1px]
              desktop:border-solid
              desktop:border-[#3F3A3A]
              desktop:text-center
              desktop:text-[20px]
              desktop:leading-[28px]
              desktop:tracking-[30px]
              desktop:text-[#3F3A3A]
              desktop:hover:text-[#8B572A]
            "
              data-name="top-nav-bar-desktop-men-dresses"
            >
              <div data-name="top-nav-bar-desktop-men-dresses-link">男裝</div>
            </div>
            <div
              classdata-name="
              mobile:hidden
              desktop:mt-[15px]
              desktop:ml-[36px]
              desktop:block
              desktop:cursor-pointer
              desktop:border-r-[1px]
              desktop:border-none
              desktop:border-[#3F3A3A]
              desktop:text-center
              desktop:text-[20px]
              desktop:leading-[28px]
              desktop:tracking-[30px]
              desktop:text-[#3F3A3A]
              desktop:hover:text-[#8B572A]
            "
              data-name="top-nav-bar-desktop-accessories"
            >
              <div data-name="top-nav-bar-desktop-accessories-link">配件</div>
            </div>

            <input
              classdata-name="
              mobile:hidden
              desktop:ml-auto
              desktop:mr-[42px]
              desktop:block
              desktop:h-[44px]
              desktop:w-[214px]
              desktop:rounded-[20px]
              desktop:border-[1px]
              desktop:border-solid
              desktop:border-[#979797]
              desktop:bg-[url('https://cdn.discordapp.com/attachments/1001702231785099304/1006055671386603581/search.png')]
              desktop:bg-right
              desktop:bg-no-repeat
              desktop:pl-[20px]
              desktop:text-[20px]
              desktop:leading-[24px]
              desktop:text-[#8B572A]
              desktop:placeholder:text-[20px]
              desktop:placeholder:leading-[24px]
              desktop:placeholder:text-[#8B572A]
            "
              type="text"
              placeholder=""
              title="search-bar"
              value=""
              data-name="top-nav-bar-desktop-search-bar"
            />

            <div
              classdata-name="
              mobile:hidden
              desktop:relative
              desktop:mr-[42px]
              desktop:flex
              desktop:h-[44px]
              desktop:w-[44px]
              desktop:cursor-pointer
              desktop:items-center
              desktop:justify-center
            "
              data-name="top-nav-bar-desktop-shopping-cart-box"
            >
              <div data-name="top-nav-bar-desktop-shopping-cart-box-link">
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1007154394585894962/image.png"
                  alt=""
                  onmouseover="this.src='https://cdn.discordapp.com/attachments/1001702231785099304/1006055626180399154/image_1_.png'"
                  onmouseout="this.src='https://cdn.discordapp.com/attachments/1001702231785099304/1007154394585894962/image.png'"
                  classdata-name=""
                  data-name="top-nav-bar-desktop-shopping-cart-image"
                />
              </div>
              <div
                classdata-name="
                absolute
                top-[45%]
                left-[45%]
                flex
                h-[24px]
                w-[24px]
                items-center
                justify-center
                rounded-[50%]
                bg-[#8b572a]
                text-[16px] leading-[24px]
                text-[#ffffff]
              "
                data-name="top-nav-bar-desktop-shopping-cart-notification-numbers"
              >
                <div
                  classdata-name="
                  absolute
                  inline-flex
                  h-full
                  w-full
                  animate-ping
                  rounded-full
                  bg-[#8b572a]
                  opacity-75
                "
                  data-name="top-nav-bar-desktop-shopping-cart-notification-animation"
                ></div>
                <div
                  classdata-name=""
                  data-name="top-nav-bar-desktop-shopping-cart-notification-numbers-text"
                >
                  1
                </div>
              </div>
            </div>

            <div data-name="top-nav-bar-desktop-profile-box">
              <img
                classdata-name="
                mobile:hidden
                desktop:mr-[54px]
                desktop:block
                desktop:h-[40px]
                desktop:w-[40px]
                desktop:cursor-pointer
              "
                src="https://cdn.discordapp.com/attachments/1001702231785099304/1007154394904666112/profile.png"
                alt=""
                onmouseover="this.src='https://cdn.discordapp.com/attachments/1001702231785099304/1006055670421925960/profile_1.png'"
                onmouseout="this.src='https://cdn.discordapp.com/attachments/1001702231785099304/1007154394904666112/profile.png'"
                data-name="top-nav-bar-desktop-profile"
              />
            </div>

            <input
              classdata-name="
              mobile:fixed
              mobile:absolute
              mobile:right-5
              mobile:z-0
              mobile:block
              mobile:h-[44px]
              mobile:w-[44px]
              mobile:rounded-[20px]
              mobile:border-[1px]
              mobile:border-none
              mobile:border-[#979797]
              mobile:bg-[url('https://cdn.discordapp.com/attachments/1001702231785099304/1006055671386603581/search.png')]
              mobile:bg-right
              mobile:bg-no-repeat
              mobile:pl-[20px]
              mobile:text-[20px]
              mobile:leading-[24px]
              mobile:text-[#8B572A]/0
              mobile:transition-all
              mobile:duration-700
              mobile:ease-in-out
              mobile:placeholder:text-[20px]
              mobile:placeholder:leading-[24px]
              mobile:placeholder:text-[#8B572A]/0
              mobile:hover:w-[calc(100%-20px)]
              mobile:hover:border-solid
              mobile:hover:text-[#8B572A]
              mobile:hover:placeholder:text-[#8B572A]
              mobile:focus:w-[calc(100%-20px)]
              mobile:focus:border-solid
              mobile:focus:text-[#8B572A]
              mobile:focus:placeholder:text-[#8B572A]
              desktop:hidden
            "
              type="text"
              placeholder=""
              title="search-bar"
              value=""
              data-name="top-nav-bar-mobile-search"
            />
          </div>

          <div
            classdata-name="
            bg-[#313538]
            mobile:flex
            mobile:h-[50px]
            mobile:items-center
            mobile:justify-evenly
            desktop:h-[40px]
          "
            data-name="top-nav-bar-below"
          >
            <div
              classdata-name="
              mobile:block
              mobile:cursor-pointer
              mobile:text-[16px]
              mobile:leading-[22px]
              mobile:text-[#828282]
              mobile:hover:text-[#ffffff]
              desktop:hidden
            "
              data-name="top-nav-bar-below-mobile-women-dresses"
            >
              <div data-name="top-nav-bar-below-mobile-women-dresses-link">
                女裝
              </div>
            </div>
            <img
              classdata-name="mobile:block desktop:hidden"
              src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055671801860126/split.png"
              alt=""
            />
            <div
              classdata-name="
              mobile:block
              mobile:cursor-pointer
              mobile:text-[16px]
              mobile:leading-[22px]
              mobile:text-[#828282]
              mobile:hover:text-[#ffffff]
              desktop:hidden
            "
              data-name="top-nav-bar-below-mobile-men-dresses"
            >
              <div data-name="top-nav-bar-below-mobile-men-dresses-link">
                男裝
              </div>
            </div>
            <img
              classdata-name="mobile:block desktop:hidden"
              src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055671801860126/split.png"
              alt=""
            />
            <div
              classdata-name="
              mobile:block
              mobile:cursor-pointer
              mobile:text-[16px]
              mobile:leading-[22px]
              mobile:text-[#828282]
              mobile:hover:text-[#ffffff]
              desktop:hidden
            "
              data-name="top-nav-bar-below-mobile-accessories"
            >
              <div data-name="top-nav-bar-below-mobile-accessories-link">
                配件
              </div>
            </div>
          </div>
        </nav>

        <div classdata-name="" data-name="main-page" id="main-page">
          <div
            classdata-name="
          w-full bg-[url('https://cdn.discordapp.com/attachments/1001702231785099304/1006055626872475758/image.png')]
          bg-cover
          bg-center
          transition-[background-image]
          duration-500
          ease-out mobile:mt-[102px]
          mobile:h-[185px] desktop:mt-[140px]
          desktop:h-[500px]
        "
            data-name="slides"
          >
            <div
              classdata-name="
            relative
            left-0
            right-0
            mx-auto
            h-full
            max-w-[1160px]
            mobile:w-[calc(100%-48px)]
          "
              data-name="slides-box"
            >
              <div
                classdata-name="absolute w-full"
                data-name="slides-slidesTextMain"
              >
                <div
                  classdata-name="
                cursor-pointer
                text-left
                mobile:mt-[36px] mobile:text-[15px] mobile:leading-[28px]
                desktop:mt-[166px]
                desktop:text-[30px]
                desktop:leading-[57px]
                desktop:text-[#070707]
              "
                  data-name="slides-text-main"
                >
                  於是
                  <br />
                  我也想要給你
                  <br />
                  一個那麼美好的自己。
                  <br />
                </div>
                <div
                  classdata-name="
                cursor-pointer
                text-left
                mobile:text-[12px] mobile:leading-[28px]
                desktop:text-[20px] desktop:leading-[64px]
              "
                  data-name="slides-text-describe"
                >
                  不朽《與自己和好如初》
                </div>
              </div>
            </div>
            <div
              classdata-name="
            absolute
            top-0
            left-0
            right-0
            mx-auto
            flex
            max-w-[1200px]
            items-center
            justify-center
            mobile:mt-[265px]
            desktop:mt-[596px]
          "
              data-name="main-page-dot-box"
            >
              <div
                classdata-name="
        cursor-pointer
        rounded-full
        bg-[#8B572A]
        bg-cover
        bg-no-repeat
        mobile:ml-[4.4px]
        mobile:mr-[4.4px]
        mobile:h-[4px]
        mobile:w-[4px]
        desktop:ml-[11px]
        desktop:mr-[11px]
        desktop:h-[10px]
        desktop:w-[10px]
        "
                data-index=""
                id=""
                data-product_id=""
                data-name="dot
        "
              ></div>
              <div
                classdata-name="
        cursor-pointer
        rounded-full
        bg-[#ffffff]/40
        bg-cover
        bg-no-repeat
        mobile:ml-[4.4px]
        mobile:mr-[4.4px]
        mobile:h-[4px]
        mobile:w-[4px]
        desktop:ml-[11px]
        desktop:mr-[11px]
        desktop:h-[10px]
        desktop:w-[10px]
        "
                data-index=""
                id=""
                data-product_id=""
                data-name="dot
        "
              ></div>
              <div
                classdata-name="
        cursor-pointer
        rounded-full
        bg-[#ffffff]/40
        bg-cover
        bg-no-repeat
        mobile:ml-[4.4px]
        mobile:mr-[4.4px]
        mobile:h-[4px]
        mobile:w-[4px]
        desktop:ml-[11px]
        desktop:mr-[11px]
        desktop:h-[10px]
        desktop:w-[10px]
        "
                data-index=""
                id=""
                data-product_id=""
                data-name="dot
        "
              ></div>
              <div
                classdata-name="
        cursor-pointer
        rounded-full
        bg-[#ffffff]/40
        bg-cover
        bg-no-repeat
        mobile:ml-[4.4px]
        mobile:mr-[4.4px]
        mobile:h-[4px]
        mobile:w-[4px]
        desktop:ml-[11px]
        desktop:mr-[11px]
        desktop:h-[10px]
        desktop:w-[10px]
        "
                data-index=""
                id=""
                data-product_id=""
                data-name="dot
        "
              ></div>
              <div
                classdata-name="
        cursor-pointer
        rounded-full
        bg-[#ffffff]/40
        bg-cover
        bg-no-repeat
        mobile:ml-[4.4px]
        mobile:mr-[4.4px]
        mobile:h-[4px]
        mobile:w-[4px]
        desktop:ml-[11px]
        desktop:mr-[11px]
        desktop:h-[10px]
        desktop:w-[10px]
        "
                data-index=""
                id=""
                data-product_id=""
                data-name="dot
        "
              ></div>
            </div>
          </div>

          <div classdata-name="flex w-full flex-col justify-center">
            <div
              classdata-name="
            flex flex-wrap
            mobile:mx-[21px]
            mobile:mt-[15px]
            mobile:w-[calc(100%-42px)]
            desktop:mx-auto
            desktop:mt-[70px]
            desktop:w-full desktop:max-w-[1200px]
          "
              data-name="main-page-product-list-box"
            >
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-1"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-2"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-3"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-4"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-5"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
              <div
                classdata-name="
              flex flex-col
              mobile:mx-[3px] mobile:w-[calc(50%-27px)]
              desktop:mx-[20px] desktop:h-[666px] desktop:w-[360px]
            "
                data-name="product-6"
              >
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055626515951719/image_2.png"
                  alt=""
                  classdata-name="
                cursor-pointer
                object-cover
                mobile:h-full mobile:w-full
                desktop:h-[480px] desktop:w-[360px]
              "
                  data-name="product-image"
                />
                <div
                  classdata-name="
                flex flex-row
                mobile:h-[40px] mobile:w-full mobile:items-center
                desktop:w-[360px]
              "
                  data-name="product-color-list"
                >
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ffffff]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color1"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#ddffbb]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color2"
                  ></div>
                  <div
                    classdata-name="
                  cursor-pointer
                  border-[1px]
                  border-solid border-[#d3d3d3] bg-[#d3d3d3]
                  mobile:mt-[8px]
                  mobile:mr-[6px]
                  mobile:h-[12px]
                  mobile:w-[12px]
                  desktop:mt-[20px]
                  desktop:mr-[10px]
                  desktop:h-[24px]
                  desktop:w-[24px]
                "
                    data-name="product-color3"
                  ></div>
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[10px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[20px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-data-name"
                >
                  前開衩扭結洋裝
                </div>
                <div
                  classdata-name="
                cursor-pointer
                mobile:mt-[8px]
                mobile:mb-[24px]
                mobile:text-[12px]
                mobile:leading-[14px]
                mobile:tracking-[2.4px]
                mobile:text-[#000000]
                desktop:mt-[10px]
                desktop:mb-[64px]
                desktop:text-[20px]
                desktop:leading-[24px]
                desktop:tracking-[4px]
                desktop:text-[#3F3A3A]
              "
                  data-name="product-price"
                >
                  TWD.799
                </div>
              </div>
            </div>
          </div>
        </div>

        <footer classdata-name="" data-name="bottom-nav">
          <div
            classdata-name="
          mobile:hidden
          desktop:z-[999]
          desktop:mx-auto
          desktop:flex
          desktop:h-[115px]
          desktop:w-full
          desktop:items-center
          desktop:justify-center
          desktop:bg-[#313538]
        "
            data-name="bottom-nav-bar-desktop-box"
          >
            <div
              classdata-name="mr-[101px] flex"
              data-name="bottom-nav-bar-desktop-links"
            >
              <div
                classdata-name="
              h-[22px]
              w-[134px]
              cursor-pointer
              border-r-[1px] border-solid border-[#828282]
              text-center
              text-[16px] leading-[22px] text-[#f5f5f5]
            "
                data-name="bottom-nav-bar-desktop-info-about"
              >
                <div data-name="bottom-nav-bar-desktop-info-about-link">
                  關於 STYLiSH
                </div>
              </div>
              <div
                classdata-name="
              h-[22px]
              w-[134px]
              cursor-pointer
              border-r-[1px] border-solid border-[#828282]
              text-center
              text-[16px] leading-[22px] text-[#f5f5f5]
            "
                data-name="bottom-nav-bar-desktop-info-service-terms"
              >
                <div data-name="bottom-nav-bar-desktop-info-service-terms-link">
                  服務條款
                </div>
              </div>
              <div
                classdata-name="
              h-[22px]
              w-[134px]
              cursor-pointer
              border-r-[1px] border-solid border-[#828282]
              text-center
              text-[16px] leading-[22px] text-[#f5f5f5]
            "
                data-name="bottom-nav-bar-desktop-privacy-policy"
              >
                <div data-name="bottom-nav-bar-desktop-privacy-policy-link">
                  隱私政策
                </div>
              </div>
              <div
                classdata-name="
              h-[22px]
              w-[134px]
              cursor-pointer
              border-r-[1px] border-solid border-[#828282]
              text-center
              text-[16px] leading-[22px] text-[#f5f5f5]
            "
                data-name="bottom-nav-bar-desktop-contact-us"
              >
                <div data-name="bottom-nav-bar-desktop-contact-us-link">
                  聯絡我們
                </div>
              </div>
              <div
                classdata-name="
              h-[22px]
              w-[134px]
              cursor-pointer
              border-none text-center text-[16px]
              leading-[22px]
              text-[#f5f5f5]
            "
                data-name="bottom-nav-bar-desktop-frequently-asked-questions"
              >
                <div data-name="bottom-nav-bar-desktop-frequently-asked-questions-link">
                  FAQ
                </div>
              </div>
            </div>
            <div
              classdata-name="flex items-center justify-center"
              data-name="bottom-nav-bar-desktop-social-media-links"
            >
              <div classdata-name="mr-[30px] h-[50px] w-[50px] cursor-pointer">
                <div data-name="bottom-nav-bar-desktop-line-image-link">
                  <img
                    src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138279856017418/line.png"
                    alt=""
                    classdata-name="h-full w-full"
                    data-name="bottom-nav-bar-desktop-line-image"
                  />
                </div>
              </div>
              <div classdata-name="mr-[30px] h-[50px] w-[50px] cursor-pointer">
                <div data-name="bottom-nav-bar-desktop-twitter-image-link">
                  <img
                    src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138279512080465/twitter.png"
                    alt=""
                    classdata-name="h-full w-full"
                    data-name="bottom-nav-bar-desktop-twitter-image"
                  />
                </div>
              </div>
              <div classdata-name="mr-[30px] h-[50px] w-[50px] cursor-pointer">
                <div data-name="bottom-nav-bar-desktop-facebook-image-link">
                  <img
                    src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138280220917851/facebook.png"
                    alt=""
                    classdata-name="h-full w-full"
                    data-name="bottom-nav-bar-desktop-facebook-image"
                  />
                </div>
              </div>
              <div
                classdata-name="text-center text-[12px] leading-[17px] text-[#828282]"
                data-name="bottom-nav-bar-desktop-all-rights-reserved"
              >
                © 2018. All rights reserved.
              </div>
            </div>
          </div>

          <div
            classdata-name="w-full bg-[#313538] mobile:z-[999] mobile:block desktop:hidden"
            data-name="bottom-nav-bar-mobile-box-box"
          >
            <div
              classdata-name="mx-auto flex max-w-[360px] flex-col items-center pt-[23px]"
              data-name="bottom-nav-bar-mobile-box"
            >
              <div
                classdata-name="flex w-full items-end justify-center"
                data-name="bottom-nav-bar-mobile-contactlist"
              >
                <div
                  classdata-name="ml-[40px] mr-[36px]"
                  data-name="bottom-nav-bar-mobile-links-part1"
                >
                  <div
                    classdata-name="mb-[8px] text-[14px] leading-[20px] text-[#D3D3D3]"
                    data-name="bottom-nav-bar-mobile-info-about"
                  >
                    <div data-name="bottom-nav-bar-mobile-info-about-link">
                      關於 STYLiSH
                    </div>
                  </div>
                  <div
                    classdata-name="mb-[8px] text-[14px] leading-[20px] text-[#D3D3D3]"
                    data-name="bottom-nav-bar-mobile-info-service-terms"
                  >
                    <div data-name="bottom-nav-bar-mobile-info-service-terms-link">
                      服務條款
                    </div>
                  </div>
                  <div
                    classdata-name="mb-[13px] text-[14px] leading-[20px] text-[#D3D3D3]"
                    data-name="bottom-nav-bar-mobile-privacy-policy"
                  >
                    <div data-name="bottom-nav-bar-mobile-privacy-policy-link">
                      隱私政策
                    </div>
                  </div>
                </div>
                <div
                  classdata-name="mr-[31px]"
                  data-name="bottom-nav-bar-mobile-links-part2"
                >
                  <div
                    classdata-name="mb-[8px] text-[14px] leading-[20px] text-[#D3D3D3]"
                    data-name="bottom-nav-bar-mobile-contact-us"
                  >
                    <div data-name="bottom-nav-bar-mobile-contact-us-link">
                      聯絡我們
                    </div>
                  </div>
                  <div
                    classdata-name="mb-[41px] text-[14px] leading-[20px] text-[#D3D3D3]"
                    data-name="bottom-nav-bar-mobile-frequently-asked-questions"
                  >
                    <div data-name="bottom-nav-bar-mobile-frequently-asked-questions-link">
                      FAQ
                    </div>
                  </div>
                </div>
                <div
                  classdata-name="mb-[51px] flex items-center justify-between"
                  data-name="bottom-nav-bar-mobile-social-media-links"
                >
                  <div classdata-name="mr-[14px] h-[20px] w-[20px]">
                    <div data-name="bottom-nav-bar-mobile-line-image-link">
                      <img
                        src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138279856017418/line.png"
                        alt=""
                        classdata-name="h-full w-full"
                        data-name="bottom-nav-bar-mobile-line-image"
                      />
                    </div>
                  </div>
                  <div classdata-name="mr-[14px] h-[20px] w-[20px]">
                    <div data-name="bottom-nav-bar-mobile-twitter-image-link">
                      <img
                        src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138279512080465/twitter.png"
                        alt=""
                        classdata-name="h-full w-full"
                        data-name="bottom-nav-bar-mobile-twitter-image"
                      />
                    </div>
                  </div>
                  <div classdata-name="mr-[24px] h-[20px] w-[20px]">
                    <div data-name="bottom-nav-bar-mobile-facebook-image-link">
                      <img
                        src="https://cdn.discordapp.com/attachments/1001702231785099304/1007138280220917851/facebook.png"
                        alt=""
                        classdata-name="h-full w-full"
                        data-name="bottom-nav-bar-mobile-facebook-image"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                classdata-name="
              mx-auto mt-[13px]
              mb-[80px]
              text-center
              text-[10px]
              leading-[14px]
              text-[#828282]
            "
                data-name="bottom-nav-bar-mobile-all-rights-reserved"
              >
                © 2018. All rights reserved.
              </div>
            </div>
          </div>

          <div
            classdata-name="
          mobile:fixed
          mobile:left-0
          mobile:bottom-0
          mobile:z-[999]
          mobile:flex
          mobile:h-[60px]
          mobile:w-full
          mobile:items-center
          mobile:justify-center
          mobile:bg-[#313538]
          desktop:hidden
        "
            data-name="bottom-nav-bar-mobile-stick"
          >
            <div
              classdata-name="
            flex
            h-[24px]
            w-[50%]
            items-center
            justify-center
            border-r-[1px] border-solid border-[#828282]
          "
              data-name="bottom-nav-bar-mobile-stick-cart"
            >
              <div
                classdata-name="
              relative
              mx-auto
              flex w-[180px]
              cursor-pointer
              flex-row
              items-center
              justify-center
            "
                data-name="bottom-nav-bar-mobile-stick-shopping-cart-box"
              >
                <div data-name="bottom-nav-bar-mobile-stick-shopping-cart-image-link">
                  <img
                    src="https://cdn.discordapp.com/attachments/1001702231785099304/1006534620352880671/image.png"
                    alt=""
                    data-name="bottom-nav-bar-mobile-stick-shopping-cart-image"
                  />
                </div>
                <div
                  classdata-name="text-center text-[16px] leading-[16px] text-[#ffffff]"
                  data-name="bottom-nav-bar-mobile-stick-shopping-cart-text"
                >
                  購物車
                </div>
                <div
                  classdata-name="
                absolute
                top-[45%]
                left-[37%]
                flex
                h-[24px]
                w-[24px]
                items-center
                justify-center
                rounded-[50%]
                bg-[#8b572a]
                text-[16px] leading-[24px]
                text-[#ffffff]
              "
                  data-name="bottom-nav-bar-mobile-stick-shopping-cart-notification-numbers"
                >
                  <div
                    classdata-name="
                  absolute
                  inline-flex
                  h-full
                  w-full
                  animate-ping
                  rounded-full
                  bg-[#8b572a]
                  opacity-75
                "
                    data-name="bottom-nav-bar-mobile-stick-shopping-cart-notification-animation"
                  ></div>
                  <div
                    classdata-name=""
                    data-name="bottom-nav-bar-mobile-stick-shopping-cart-notification-numbers-text"
                  >
                    1
                  </div>
                </div>
              </div>
            </div>
            <div
              classdata-name="
            relative
            mx-auto
            flex w-[180px]
            cursor-pointer
            flex-row
            items-center
            justify-center
          "
              data-name="bottom-nav-bar-mobile-stick-shopping-profile-box"
            >
              <div data-name="bottom-nav-bar-mobile-stick-shopping-profile-box-link">
                <img
                  src="https://cdn.discordapp.com/attachments/1001702231785099304/1006055670895890453/profile.png"
                  alt=""
                  data-name="bottom-nav-bar-mobile-stick-shopping-profile-box-image"
                />
              </div>
              <div
                classdata-name="text-center text-[16px] leading-[16px] text-[#ffffff]"
                data-name="bottom-nav-bar-mobile-stick-shopping-profile-box-text"
              >
                會員
              </div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
};

export default Home;
