/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ProductLazyImport = createFileRoute('/Product')()
const CheckoutLazyImport = createFileRoute('/Checkout')()

// Create/Update Routes

const ProductLazyRoute = ProductLazyImport.update({
  id: '/Product',
  path: '/Product',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Product.lazy').then((d) => d.Route))

const CheckoutLazyRoute = CheckoutLazyImport.update({
  id: '/Checkout',
  path: '/Checkout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Checkout.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Checkout': {
      id: '/Checkout'
      path: '/Checkout'
      fullPath: '/Checkout'
      preLoaderRoute: typeof CheckoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/Product': {
      id: '/Product'
      path: '/Product'
      fullPath: '/Product'
      preLoaderRoute: typeof ProductLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutLazyRoute
  '/Product': typeof ProductLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutLazyRoute
  '/Product': typeof ProductLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutLazyRoute
  '/Product': typeof ProductLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Checkout' | '/Product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Checkout' | '/Product'
  id: '__root__' | '/' | '/Checkout' | '/Product'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutLazyRoute: typeof CheckoutLazyRoute
  ProductLazyRoute: typeof ProductLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutLazyRoute: CheckoutLazyRoute,
  ProductLazyRoute: ProductLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Checkout",
        "/Product"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Checkout": {
      "filePath": "Checkout.lazy.tsx"
    },
    "/Product": {
      "filePath": "Product.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
